### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by Allenisdabest** [TheCosmic04/Minecraft-Screen#6]
after i followed the steps to setup the client i got an error after i did node client.js it says Module Not Found (Note: i already downloaded the node js client)
Heres the log:
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'C:\Users\acer\client.js'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:745:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}

**Comment by blockyenperor34** [comment]
`cd nodejs `
`node client.js`
and it works

**Comment by Allenisdabest** [comment]
thank you that worked
